### ISSUE TITLE
when subscribing to Sensor_info topic it causes a trace in takktile_node.py

### ISSUE THREAD

**Issue by ablasdel** [harvardbiorobotics/takktile_ros#2]
This line seems to pass a 2d array (self.alive) to the publisher here: https://github.com/harvardbiorobotics/takktile_ros/blob/master/src/takktile_node.py#L125

but the message is expecting a 1d array:
https://github.com/harvardbiorobotics/takktile_ros/blob/master/msg/Info.msg

It looks like either 1 info message needs to be published per Takktile instance or the info message needs to be built to accommodate an array of the current info messages.

The error that occurs once the topic is accessed:

```
contact threshold: 5
temp lowpass: 0.001
[INFO] [WallTime: 1423771663.824648] /takktile_24852_1423771663689 node initialized
Number of boards found =  1
UIDs  [u'435543438323FFFFA0FFC1006100']
Traceback (most recent call last):
  File "/home/user/rosmake_ws/takktile_ros/src/takktile_node.py", line 225, in <module>
    TakkNode(XYZ_MAP, FRAME_ID, TEMPERATURE_LOWPASS, CONTACT_THRESHOLD)
  File "/home/user/rosmake_ws/takktile_ros/src/takktile_node.py", line 125, in __init__
    info_pub.publish(frame_id, xyz_map, self.alive )
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 802, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field indexes[] must be an integer type
```

**Comment by p93sb** [comment]
Hello,
I'm integrating tactiles sensors in ROS and I have found the same problem as you. Have you found a solution to it?

Thanks for your help

**Comment by ablasdel** [comment]
At the moment I am not using takktiles, when I was if I had solved this I probably would have opened a pull request. Sorry! 

I doubt a lot is depending on this package so changing the message is probably acceptable. You should try that.
